---
- name: Configure CSR Routers
  hosts: routers
  collections:
  - cisco.ios
  tasks:
    - name: Configure BGP
      ios_bgp:
        config:
        - bgp_as: 65001
          router_id: "{{ router_id }}"
          #log_neighbor_changes: true
        #  neighbors:
        #  - neighbor: "{{ item.value }}"
        #    remote_as: 65001
        #    description: "neighbor {{ item.key }}"
        #loop: "{{ neighbors | dict2items }}"  
