---
- name: Configure CSR Routers
  hosts: routers
  collections:
  - cisco.ios
  tasks:
    - name: Configure IP address on Gig2
      ios_l3_interfaces:
        config:
        - name: GigabitEthernet2
          ipv4:
          - address: "{{ ip_addr }}"
    - name: enable interfaces
      ios_interfaces:
        config:
        - name: GigabitEthernet2
          enabled: true
    - name: Configure IP address on Loopback0
      ios_l3_interfaces:
        config:
        - name: Loopback0
          ipv4:
          - address: "{{ loopbacks }}"



