---
- name: Configure CSR Routers
  hosts: routers
  collections:
  - cisco.ios
  tasks:
    - name: Configure BGP
      ios_bgp:
        config:
          bgp_as: 65001
          router_id: "{{ router_id }}"
          #log_neighbor_changes: true

    - name: configure BGP neighbors
      ios_bgp:
        config:
          bgp_as: 65001
          neighbors:
          - neighbor: "{{ item.value }}"
            remote_as: 65001
            description: "neighbor {{ item.key }}"
      loop: "{{ neighbors | dict2items }}"

    - name: Configure networks
      ios_bgp:
        config:
          bgp_as: 65001
          networks:
          - prefix: "{{ prefix }}"
            masklen: 24