---
all:
  children:
    routers:
      children:
        r1:
          hosts: 172.16.1.112
        r2:
          hosts: 172.16.1.117
        r3:
          hosts: 172.16.1.123
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_user: wwt
        #lookup_intf: GigabitEthernet1
        #dns_server: 8.8.8.8

