---

- name: Configure CSR interface
  hosts: routers
  connection: network_cli
  gather_facts: False
  tasks:
    - name: Configure GigabitEthernet2
      cisco.ios.ios_l3_interfaces:
        config:
          - name: GigabitEthernet2
            ipv4:
            - address: "{{ ip_addr }}"
    - name: enable interfaces
      ios_interfaces:
        config:
          - name: GigabitEthernet2
            enabled: true
