---
- name: Configure name servers
  hosts: routers
  collections:
  - cisco.ios
  tasks:
    - name: configure lookup sources
      ios_system:
        lookup_source: {{ lookup_inft }}
        lookup_enabled: yes
    - name: configure name servers
      ios_system:
        name_servers: {{ dns_server }}