---
- name: use pyats to find bgp info
  hosts: routers
  collections:
  - ansible.netcommon
  tasks:
    - name: get bgp info
      cli_parse:
        command: show ip bgp neighbors
        parser:
          name: pyats
        set_fact: interfaces

    
