---
- name: use pyats to find bgp info
  hosts: routers
  roles:
  - ansible-pyats
  tasks:
    - name: run show bgp neighbors
      cli_command:
        command: show bgp neighbors
      register: cli_output
    - name: parsing ouput
      set_fact:
        parsing_output: "{{ cli_output.stdout | pyats_parser('show bgp neighbors', 'iosxe') }}"
    - name: debug
      debug:
        var: "{{ parsing_output.stdout }}"
