---
- name: use pyats to find bgp info
  hosts: routers
  roles:
  - ansible-pyats
  tasks:
    - name: run show bgp neighbors
      cli_command:
        command: show ip bgp neighbors
      register: cli_output
    - name: debug
      debug:
        var: "{{ cli_output.stdout | pyats_parser('show ip bgp neighbors', 'iosxe') }}"
    #- name: print bgp neighbors
    #  #register: "{{ parsing_output | subelements('list_of_neighbors') }}"
    #  debug:
    #    #var: "{{ parsing_output | community.general.json_query('list_of_neighbors[].name') }}" 
    #    var: "{{ parsing_output }}" 
