---
- name: use pyats to find bgp info
  hosts: routers
  collections:
  roles:
  - ansible-pyats
  tasks:
    - pyats_parse_command:
        command: show ip route bgp
      register: output
    - debug:
        var: output.structured

    
