---
- name: use pyats to find bgp info
  hosts: routers
  roles:
  - ansible-pyats
  tasks:
    - name: run show bgp summary
      cli_command:
        command: show bgp summary
      register: cli_output
    - name: parsing output
      set_fact:
        parsed_output: "{{ cli_output.stdout | pyats_parser('show bgp summary') }}"