---
- name: use pyats to find bgp info
  hosts: routers
  roles:
  - ansible-pyats
  tasks:
    - name: run show bgp neighbors
      cli_command:
        command: show bgp neighbors
      register: cli_output
    - name: debug
      set_fact:
        parsing_output: "{{ cli_output.stdout | pyats_parser('show bgp neighbors', 'iosxe') }}"
    - name: print bgp neighbors
      #register: "{{ parsing_output | subelements('list_of_neighbors') }}"
      debug:
        var: "{{ parsing_output | community.general.json_query('list_of_neighbors') }}" 
