---
- name: use pyats to find bgp info
  hosts: routers
  collections:
  roles:
  - ansible-pyats
  tasks:
    - pyats_parse_command:
        command: show ip bgp neighbors
      #register: output
      parser:
        name: ansible.netcommon.json
      register: list_of_neighbors
    #- debug:
    #   var: output.structured
    - name: parsing output


    
