---
- name: Configure CSR Routers
  hosts: routers
  collections:
  - cisco.ios
  tasks:
    - name: remove bgp as 65001
      ios_bgp:
        config:
          bgp_as: 65001
        operation: delete
    - name: Configure IP address on Loopback0
      ios_config:
        lines:
        - no interface {{ item.key }}
      loop: "{{ loopbacks | dict2items }}"




