---
- name: Configure CSR Routers
  hosts: routers
  collections:
  - cisco.ios
  tasks:
    - name: remove bgp as 65001
      ios_bgp:
        config:
          bgp_as: 65001
        operation: delete
    - name: remove loopback interfaces
      ios_interfaces:
        config:
          name: {{ item.key }}
        state: deleted
      loop: "{{ loopbacks | dict2items }}"




