---
- name: Configure CSR Routers
  hosts: routers
  collections:
  - cisco.ios
  tasks:
    - name: remove bgp as 65001
      ios_bgp:
        config:
          bgp_as: 65001
        operation: delete
    - name: delete loopback IP addresses
      ios_l3_interfaces:
        config:
        - name: "{{ item.key }}"
        state: deleted
      loop: "{{ loopbacks | dict2items }}"
      notify: delete loopbacks
    - name: disable int Gig2
      ios_l3_interfaces:
        config:
        - name: GigabitEthernet2
        state: deleted

  handlers:
    - name: delete loopbacks
      ios_config:
        lines:
        - no interface "{{ item.key }}"
      loop: "{{ loopbacks | dict2items }}"
        




