---
- name: Configure CSR Routers
  hosts: routers
  collections:
  - cisco.ios
  tasks:
    - name: remove bgp as 65001
      ios_bgp:
        config:
          bgp_as: 65001
        operation: delete
    - name: delete loopback addresses
      ios_config:
        lines:
        - no interface {{ item.key }}
      loop: "{{ loopbacks | dict2items }}"
    - name: disable int Gig2
      ios_interfaces:
        config:
        - name: GigabitEthernet2
        state: deleted




